version: '3'
#test
services:
  webshell-front:
    build:
      context: ./webshell-front
      dockerfile: ./webshell-front.Dockerfile
    restart: always
    ports:
    - "8080:80"
    environment:
      FRONT_PORT: "80"
      WS_PROTOCOL: "ws"
      WS_HOST: "webshell-ws:8081"
    deploy:
      mode: replicated
      replicas: 1
  webshell-ws:
    build:
      context: ./webshell-ws
      dockerfile: ./webshell-ws.Dockerfile
      args:
        ROOT_CMD: "websh"
    ports:
    - "8081:8081"
    environment:
      WS_PORT: "8081"
      ROOT_CMD: "websh"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
